imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/config.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  snc_redis.session.handler
#        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
easy_admin:
#    disabled_actions: ['delete', 'edit', 'new']
    site_name: Siplo
    design:
        assets:
            favicon: '/assets/backend/favicon.png'
    list:
        actions:
            - { name: 'show', icon: 'search', label: 'Show'}
            - { name: 'edit', icon: 'pencil', label: 'Edit' }
            - { name: 'delete', icon: 'trash', label: 'Delete' }
            - { name: 'search', icon: 'search', label: 'Search' }
    entities:
      Teacher:
        class: UserBundle\Entity\Teacher
        label: 'Teachers'
        list:
          title: 'Teachers'
          fields:
            - id
            - username
            - { property: 'email', type: 'email' }
            - enabled
            - lastLogin
        edit:
          title: 'Edit Teacher'
          fields: ['username', 'email', 'roles']
        form:
          fields: ['enabled', 'username', 'email', 'plainPassword', 'roles', 'lastLogin']

      Student:
        class: UserBundle\Entity\Student
        label: 'Students'
        list:
          title: 'Students'
          fields:
            - id
            - username
            - { property: 'email', type: 'email' }
            - enabled
            - lastLogin
        edit:
          title: 'Edit Student'
          fields: ['username', 'email', 'batch', 'roles']
        form:
          fields: ['enabled', 'username', 'email', 'plainPassword', 'roles', 'lastLogin']

      Batch:
        class: AppBundle\Entity\Batch
        label: 'Batches'
        list:
          title: 'Batches'
        new:
          title: 'New Batch'
        edit:
          title: 'Edit Batch'
        delete:
          title: 'Delete Batch'


      Course:
        class: AppBundle\Entity\Course
        label: 'Courses'

        list:
          title: 'Courses'
        new:
          title: 'New Courses'
        edit:
          title: 'Edit Courses'
        delete:
          title: 'Delete Courses'


      Module:
        class: AppBundle\Entity\Module
        label: 'Modules'

        list:
          title: 'Modules'
        new:
          title: 'New Module'
        edit:
          title: 'Edit Module'
        delete:
          title: 'Delete Module'

      Sesssion:
        class: AppBundle\Entity\Session
        label: 'Sessions'

        list:
          title: 'Sessions'
        new:
          title: 'New Session'
        edit:
          title: 'Edit Session'
        delete:
          title: 'Delete Session'

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
            logging: %kernel.debug%
        cache:
            type: predis
            alias: cache
            dsn: redis://localhost/1
    session:
        client: default
        prefix: edu:
