services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    siplo_user.registration_listener:
        class: UserBundle\EventListener\RegistrationListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }


#To loging_success hander to work, 'use_referer' and 'success_handler' should be set in security.yml:firewall:main
#snipped from : https://gist.github.com/marydn/8061424
    siplo_login_success_handler:
        class:  UserBundle\Services\LoginSuccessHandler
        arguments:  ["@router", "@security.authorization_checker"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }